In [37]:
import pandas as pd
import numpy as np

In [38]:
np.random.seed(0)
# without seed .random produce diffrent result each time we run the code
# with seed .random produce same result each time we run the code
# Here the value in .seed() can be any integer, it is just used to initialize the random number generator
# like from where to start generating random numbers


df = pd.DataFrame({
    "age":np.random.randint(18,70,size=10).astype(float),
    "salary":np.random.randint(50000,1150000,size=10),
    "city":["A","B","A","C","B","A","C","B","A","C"],
    "join_date":pd.date_range(start="2020-01-01", periods=10)
})
df

    age  salary city  join_date
0  62.0  424564    A 2020-01-01
1  65.0  785831    B 2020-01-02
2  18.0  786326    A 2020-01-03
3  21.0  360744    C 2020-01-04
4  21.0  889052    B 2020-01-05
5  57.0  654474    A 2020-01-06
6  27.0  591377    C 2020-01-07
7  37.0  999734    B 2020-01-08
8  39.0  724343    A 2020-01-09
9  68.0  420775    C 2020-01-10

In [39]:
#injecting some null values
df.loc[[1,2,5],"age"] = np.nan
df.loc[[2,7],"salary"] = np.nan
df.loc[[3,5],"city"] = np.nan

df

    age    salary city  join_date
0  62.0  424564.0    A 2020-01-01
1   NaN  785831.0    B 2020-01-02
2   NaN       NaN    A 2020-01-03
3  21.0  360744.0  NaN 2020-01-04
4  21.0  889052.0    B 2020-01-05
5   NaN  654474.0  NaN 2020-01-06
6  27.0  591377.0    C 2020-01-07
7  37.0       NaN    B 2020-01-08
8  39.0  724343.0    A 2020-01-09
9  68.0  420775.0    C 2020-01-10

In [40]:
#some results
df.isnull().sum()

age          3
salary       2
city         2
join_date    0
dtype: int64

In [41]:

df.count()

age           7
salary        8
city          8
join_date    10
dtype: int64

In [42]:
df.isnull().mean()

age          0.3
salary       0.2
city         0.2
join_date    0.0
dtype: float64

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        7 non-null      float64
 1   salary     8 non-null      float64
 2   city       8 non-null      str
 3   join_date  10 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(2), str(1)
memory usage: 452.0 bytes

In [44]:
#drop columns which have null mean more than 0.4
drop_cols = df.columns[df.isnull().mean()>0.4]
df.drop(columns=drop_cols, inplace=True)
df

    age    salary city  join_date
0  62.0  424564.0    A 2020-01-01
1   NaN  785831.0    B 2020-01-02
2   NaN       NaN    A 2020-01-03
3  21.0  360744.0  NaN 2020-01-04
4  21.0  889052.0    B 2020-01-05
5   NaN  654474.0  NaN 2020-01-06
6  27.0  591377.0    C 2020-01-07
7  37.0       NaN    B 2020-01-08
8  39.0  724343.0    A 2020-01-09
9  68.0  420775.0    C 2020-01-10

In [45]:
#dropping rows with null values sum >=2
df.dropna(thresh=2, inplace=True)
#or
df[df.isnull().sum(axis=1)<2]
df

    age    salary city  join_date
0  62.0  424564.0    A 2020-01-01
1   NaN  785831.0    B 2020-01-02
2   NaN       NaN    A 2020-01-03
3  21.0  360744.0  NaN 2020-01-04
4  21.0  889052.0    B 2020-01-05
5   NaN  654474.0  NaN 2020-01-06
6  27.0  591377.0    C 2020-01-07
7  37.0       NaN    B 2020-01-08
8  39.0  724343.0    A 2020-01-09
9  68.0  420775.0    C 2020-01-10

In [46]:
#fill the nan with values
df['age'] = df['age'].fillna(df['age'].median())

df['city'] = df['city'].fillna(df['city'].mode()[0])
df

    age    salary city  join_date
0  62.0  424564.0    A 2020-01-01
1  37.0  785831.0    B 2020-01-02
2  37.0       NaN    A 2020-01-03
3  21.0  360744.0    A 2020-01-04
4  21.0  889052.0    B 2020-01-05
5  37.0  654474.0    A 2020-01-06
6  27.0  591377.0    C 2020-01-07
7  37.0       NaN    B 2020-01-08
8  39.0  724343.0    A 2020-01-09
9  68.0  420775.0    C 2020-01-10

In [47]:
df_backup = df.copy()

# Without .copy():
#     👉 Both variables point to the same data in memory
#         So if you change one, the other also changes ❌
        
# 👉 Now:

# df_backup is a new object
# Changes in df will NOT affect df_backup
df_backup

    age    salary city  join_date
0  62.0  424564.0    A 2020-01-01
1  37.0  785831.0    B 2020-01-02
2  37.0       NaN    A 2020-01-03
3  21.0  360744.0    A 2020-01-04
4  21.0  889052.0    B 2020-01-05
5  37.0  654474.0    A 2020-01-06
6  27.0  591377.0    C 2020-01-07
7  37.0       NaN    B 2020-01-08
8  39.0  724343.0    A 2020-01-09
9  68.0  420775.0    C 2020-01-10

In [48]:

from sklearn.impute import SimpleImputer

# What problem does it solve?

# Imagine you want to:

# Predict house prices 🏠
# Classify emails as spam/not spam 📧
# Group customers into segments 👥

# 👉 You could write all ML algorithms yourself…
# ❌ But that’s complex and time-consuming

# 👉 Scikit-learn gives ready-made implementations ✅

# for eg from sklearn.linear_model import LinearRegression

# When NOT to use it
# Deep learning → use TensorFlow / PyTorch
# Very large-scale systems → may need specialized tools

# SimpleImputer in scikit-learn is used to fill missing values in a dataset.

# 1. Numeric columns
num_imp = SimpleImputer(strategy="median") #or mean depends on data

# 2. Categorical columns (most frequent) 
cat_imp_mfreq = SimpleImputer(strategy="most_frequent") #or mode
cat_imp_const = SimpleImputer(strategy="constant",fill_value="Missing")


df['age'] = num_imp.fit_transform(df[['age']])[:, 0]
df['city'] = cat_imp_mfreq.fit_transform(df[['city']])[:, 0]
# SimpleImputer expects 2D input, and df[['age']] gives 2D. not df['age']

In [49]:
df

    age    salary city  join_date
0  62.0  424564.0    A 2020-01-01
1  37.0  785831.0    B 2020-01-02
2  37.0       NaN    A 2020-01-03
3  21.0  360744.0    A 2020-01-04
4  21.0  889052.0    B 2020-01-05
5  37.0  654474.0    A 2020-01-06
6  27.0  591377.0    C 2020-01-07
7  37.0       NaN    B 2020-01-08
8  39.0  724343.0    A 2020-01-09
9  68.0  420775.0    C 2020-01-10

In [ ]:
# Dealing with TimeFrame
# It is good to replace the NaN or Missing time with the data of prev time or next TimeFrame.

In [ ]:
# df['salary'] = df['salary'].fillna(method='ffill') 
# or 
df = df.sort_values('join_date') # Ensure data is sorted by time
df['salary'] = df['salary'].ffill()

# Here all the salary datas are also sorted according to date so we fill the salary of missing value 
# with the salary of previous date.

df

    age    salary city  join_date
0  62.0  424564.0    A 2020-01-01
1  37.0  785831.0    B 2020-01-02
2  37.0  785831.0    A 2020-01-03
3  21.0  360744.0    A 2020-01-04
4  21.0  889052.0    B 2020-01-05
5  37.0  654474.0    A 2020-01-06
6  27.0  591377.0    C 2020-01-07
7  37.0  591377.0    B 2020-01-08
8  39.0  724343.0    A 2020-01-09
9  68.0  420775.0    C 2020-01-10

Strategy MultiVariate Imputation
Here we cant replace the missing valus with the independent mean or statistice of that single column only rather we have to consider
relatioship between other columns depends on also.

We can use IterativeImputer or KNN Imputer



👉 SimpleImputer fills missing values using one simple rule
👉 IterativeImputer fills missing values by learning patterns from other features


| Age | Salary |
| --- | ------ |
| 25  | 30000  |
| 30  | 40000  |
| 35  | NaN    |

Now salary is missing.

SimpleImputer
might fill with median salary:
35000

IterativeImputer

looks at pattern:

age 25 → salary 30000
age 30 → salary 40000

Then predicts:
age 35 → salary ≈ 50000
This is smarter.



IterativeImputer takes one target column where it should replace values and othres as supportive to calculate so we first handle the supoort column misisng values with mean,median or mode or any other

In [53]:
df = pd.DataFrame({
    'MedInc': [8.3, 8.0, np.nan, 5.5, 3.8, np.nan, 7.0],   # Median Income
    'HouseAge': [41, 21, 52, np.nan, 52, 15, 30],          # Age of the house
    'MedHouseVal': [4.5, 3.5, 3.5, 3.4, np.nan, 2.8, 3.0] # Median House Value
})

df

   MedInc  HouseAge  MedHouseVal
0     8.3      41.0          4.5
1     8.0      21.0          3.5
2     NaN      52.0          3.5
3     5.5       NaN          3.4
4     3.8      52.0          NaN
5     NaN      15.0          2.8
6     7.0      30.0          3.0

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imp = IterativeImputer()

# Create the imputer object.

# By default it:
# uses a regression model internally
# predicts missing values using other columns
# repeats multiple times to refine predictions

df_imputed = pd.DataFrame(imp.fit_transform(df), columns=df.columns)
# This is the main step.

# 1. imp.fit_transform(df)
# looks at all columns
# finds missing values
# predicts them using other columns
# returns a filled NumPy array

# 2. pd.DataFrame(..., columns=df.columns)
# fit_transform() returns only a NumPy array, so column names are lost.
# This converts it back into a DataFrame and restores original column names.

df_imputed

c:\Users\sibasis.badatya\Documents\python\.venv\Lib\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

array([[ 8.3       , 41.        ,  4.5       ],
       [ 8.        , 21.        ,  3.5       ],
       [ 5.45913492, 52.        ,  3.5       ],
       [ 5.5       , 48.89729812,  3.4       ],
       [ 3.8       , 52.        ,  2.59211342],
       [ 7.67936692, 15.        ,  2.8       ],
       [ 7.        , 30.        ,  3.        ]])

KNNImputer in scikit-learn fills missing values by looking at similar rows.

KNN = K Nearest Neighbors

So the idea is:

👉 find rows that look similar
👉 use them to fill the missing value

Simple intuition

Suppose one student’s math marks are missing.

You look for students with similar:

science marks
english marks
attendance

Then estimate the missing math mark using those similar students.

That is exactly how KNNImputer works.


How it works
--------------------------------

For a missing value:

Step 1

Find rows similar to this row

Step 2

Pick nearest K rows
(K = number of neighbors)

Step 3

Use their values to fill missing value

Usually by averaging them.

In [57]:
df

   MedInc  HouseAge  MedHouseVal
0     8.3      41.0          4.5
1     8.0      21.0          3.5
2     NaN      52.0          3.5
3     5.5       NaN          3.4
4     3.8      52.0          NaN
5     NaN      15.0          2.8
6     7.0      30.0          3.0

In [58]:
from sklearn.impute import KNNImputer

knn_imp = KNNImputer(n_neighbors=2)
df_knn_imp = pd.DataFrame(knn_imp.fit_transform(df), columns=df.columns)
df_knn_imp

   MedInc  HouseAge  MedHouseVal
0    8.30      41.0         4.50
1    8.00      21.0         3.50
2    4.65      52.0         3.50
3    5.50      33.5         3.40
4    3.80      52.0         3.45
5    6.75      15.0         2.80
6    7.00      30.0         3.00

----------------------------------------------------------------
How Both Itertive Imputer Works
----------------------------------------------------------------

| Age | Experience | Salary |
| --- | ---------- | ------ |
| 25  | 2          | 30000  |
| 30  | 5          | 50000  |
| 35  | 7          | NaN    |

Salary is missing.

Instead of filling with average salary, IterativeImputer thinks:

👉 Salary probably depends on:

Age
Experience

So it learns pattern:
Salary = f(Age, Experience)

Step-by-step working
Step 1: Initial fill (rough guess)

First, it quickly fills all missing values with simple estimates
(like mean).

So missing values get temporary placeholders.

| Age | Experience | Salary    |                   |
| --- | ---------- | --------- | ----------------- |
| 25  | 2          | 30000     |                   |
| 30  | 5          | 50000     |                   |
| 35  | 7          | **40000** | ← temporary guess |

Step 2: Pick one column with missing values

Now it selects one column (say Salary) and treats it as target.

It says:

👉 let me predict Salary using other columns

So:

target = Salary
inputs = Age, Experience


Step 3: Train a model

It trains a small regression model using rows where Salary is known.

From known rows:

| Age | Experience | Salary |
| --- | ---------- | ------ |
| 25  | 2          | 30000  |
| 30  | 5          | 50000  |


It learns relation:

👉 higher age + more experience → higher salary

Step 4: Predict missing value

Now it predicts missing Salary for:

Age	Experience
35	7

Now temporary 40000 gets replaced with smarter 65000.

Step 5: Move to next column

Then it repeats same process for another column with missing values.

Example:

predict missing Age using Experience, Salary
predict missing Experience using Age, Salary

So every column gets improved one by one.

-----------------------------------------------------------------
That is exactly how KNNImputer works.
--------------------------------------------------------------------


| Age | Experience | Salary |
| --- | ---------- | ------ |
| 25  | 2          | 30000  |
| 30  | 5          | 50000  |
| 35  | 6          | NaN    |

Salary is missing in row 3.

We want to fill it.
Step-by-step how KNNImputer works

Step 1: Find the row with missing value
| Age | Experience | Salary |
| --- | ---------- | ------ |
| 35  | 6          | NaN    |


Step 2: Compare this row with other rows

Now compare this row with rows where Salary is known.

| Age | Experience |
| --- | ---------- |
| 25  | 2          |

Difference from missing row (35, 6) is large.

So row 1 is not very similar.

Compare with row 2

| Age | Experience |
| --- | ---------- |
| 30  | 5          |

This is much closer to (35, 6).

So row 2 is more similar.

Step 3: Find nearest neighbors

Now choose the nearest rows (most similar rows).
if n_neighbors = 2

take the 2 closest rows.

These are the K nearest neighbors.

Now look at their Salary values:

row 1 → 30000
row 2 → 50000

Use them to estimate missing Salary.

Usually by averaging.
(30000 + 50000) / 2 = 40000

Missing Salary becomes 40000.






| Aspect                           | IterativeImputer                            | KNNImputer                                     |
| -------------------------------- | ------------------------------------------- | ---------------------------------------------- |
| **How it fills missing values**  | Predicts missing values using other columns | Fills using values from similar rows           |
| **Core idea**                    | Learns feature relationships                | Finds nearest neighbors                        |
| **Method type**                  | Model-based (regression)                    | Distance-based                                 |
| **Looks at**                     | Column relationships                        | Row similarity                                 |
| **Best when**                    | Features are correlated                     | Similar rows exist                             |
| **Example thinking**             | “Predict salary using age + experience”     | “Find similar people and use their salary”     |
| **Captures feature dependency?** | Yes                                         | Partially                                      |
| **Uses global pattern?**         | Yes (whole dataset)                         | No (local neighbors only)                      |
| **Uses local similarity?**       | No                                          | Yes                                            |
| **Speed**                        | Moderate                                    | Slower on large data                           |
| **Scaling needed?**              | Optional                                    | Very important                                 |
| **Why scaling matters**          | Model can adjust weights                    | Distance gets dominated by large-scale columns |
| **Output quality**               | Better when columns are related             | Better when similar rows exist                 |
| **Good for**                     | Structured/tabular correlated data          | Clustered / similarity-based data              |
| **Main strength**                | Smarter feature-based prediction            | Natural neighbor-based filling                 |
| **Main weakness**                | Slower, more complex                        | Slow + sensitive to scaling                    |